# Generated by Django 5.2.3 on 2026-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
