# Generated by Django 5.2.3 on 2026-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_order_id_alter_orderitem_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('button_text', models.CharField(default='Ver colección', max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
