# Generated by Django 5.2.3 on 2026-08-23 15:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_status_from_is_paid(apps, schema_editor):
    Order = apps.get_model('products', 'Order')
    Order.objects.filter(is_paid=True).update(status='pagado')
    Order.objects.filter(is_paid=False).update(status='pendiente')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Portada', 'verbose_name_plural': 'Portada'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item del pedido', 'verbose_name_plural': 'Items del pedido'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de producto'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Variante', 'verbose_name_plural': 'Variantes'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('preparacion', 'Preparación en curso'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del pedido'),
        ),
        migrations.RunPython(backfill_status_from_is_paid, noop),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden en el catálogo (menor = primero)', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(default='Ver colección', max_length=50, verbose_name='Texto del botón'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Talle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Talle'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
